import Head from 'next/head';
import { useEffect, useRef, useState } from 'react';
import styles from '../styles/Home.module.css';

export async function getStaticProps() {
  return {
    props: {
      // default the map to Missoula, MT coords
      address: 'Missoula, MT, US',
      center: { lat: 46.8721, lng: -113.994 },
    },
  };
}

function Map({ center }) {
  const ref = useRef();
  const [map, setMap] = useState();

  const ZOOM = 9;

  useEffect(() => {
    if (ref.current && !map) {
      const newMap = new window.google.maps.Map(ref.current, {
        zoom: ZOOM,
        center,
      });

      const waqiMapOverlay = new google.maps.ImageMapType({
        getTileUrl: function (coord, zoom) {
          return `https://tiles.aqicn.org/tiles/usepa-aqi/${zoom}/${coord.x}/${coord.y}.png?token=${process.env.NEXT_PUBLIC_AQICN_API_KEY}`;
        },
        name: 'Air Quality',
      });

      newMap.overlayMapTypes.insertAt(0, waqiMapOverlay);

      setMap(newMap);
    }
  }, [ref, map, center]);

  return <div ref={ref} className={styles.map} />;
}

export default function Home({ address, center }) {
  return (
    <>
      <Head>
        <title>Current AQI for {address}</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="https://www.learnwithjason.dev/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="https://www.learnwithjason.dev/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="https://www.learnwithjason.dev/favicon-16x16.png"
        />
      </Head>

      <section className={styles.container}>
        <header className={styles.header}>
          <h1>Showing Current Air Quality Index for {address}</h1>
          <p>
            This is a demo of updating a map to show air quality data for the
            user’s current location using{' '}
            <a href="https://docs.netlify.com/integrations/frameworks/next-js/middleware/">
              Next.js Advanced Middleware
            </a>
            , powered by{' '}
            <a href="https://docs.netlify.com/edge-functions/overview/">
              Netlify Edge Functions
            </a>
            .
          </p>
        </header>
        <Map center={center} />
        <footer className={styles.footer}>
          <p>
            built with love and boops by{' '}
            <a href="https://jason.af/">Jason Lengstorf</a>
          </p>
          <nav>
            <a href="https://aqicn.org/api/">AQI data</a>
            <a href="https://github.com/jlengstorf/air-quality-edge-functions">
              source code
            </a>
          </nav>
        </footer>
      </section>
    </>
  );
}
